name: Python Application Tests

# on:
#   push:
#     branches: [ "main" ] # Or your primary branch name, e.g., master
#   pull_request:
#     branches: [ "main" ] # Or your primary branch name

permissions:
  contents: read

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # Start with ubuntu, can add windows-latest, macos-latest later
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies (for PyAudio, etc. on Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev libasound2-dev ffmpeg
      # For ffmpeg, it's often better to use a pre-built action or ensure it's available.
      # GitHub-hosted runners often have ffmpeg pre-installed.
      # Adding ffmpeg here just in case, but might not be strictly needed if runner has it.

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s tests -p "test_*.py"